# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'kefu' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for kefu
  
  # 第一步：添加pod库
  # 集成萝卜丝核心协议库core
  pod 'bytedesk-core', '2.0.2'
  # 集成萝卜丝UI库
  pod 'bytedesk-ui', '2.0.2'

  target 'kefuTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
